### PR TITLE
fix: allow for nullable property access

### LINKED ISSUE #1: Null safety in getters
Per README:

> ## Null-Safety
>
> Expressions are generally null-safe. If a subexpression yields null or undefined, subsequent property access will return null, rather than throwing an exception. Property access, method invocation and operators are null-safe. Passing null to a function that doesn't handle null will not be null safe.

However, Try:

```js
import { parse, EvalAstFactory } from 'jexpr';

const a = new EvalAstFactory();
const e = parse('data.nullableParam.nullable', a);
console.log(e.evaluate({ data: null }));
```

**expect** "null" or maybe empty string.  
**actual** `Uncaught TypeError: can't access property "nullableParam", this.receiver.evaluate(...) is null`

repro:

https://repl.it/@bennypowers/jexpr-null-exception#script.js

### PR DESCRIPTION
**Pull request by bennypowers**
## What I Did:

- Use `?.` optional chaining to access the results of `this.receiver.evaluate()`
- update the type of `parse` to take a type instance of `Expression`
- ran prettier

fixes #1

### CODE REVIEW

**Comment by bennypowers** [comment]
## Benchmarks:

### Branch:

```
eval identifier x 873,475,268 ops/sec ±0.55% (93 runs sampled)
native identifier x 851,146,029 ops/sec ±1.57% (86 runs sampled)
eval complex x 6,903,084 ops/sec ±2.19% (86 runs sampled)
native complex x 847,210,764 ops/sec ±1.12% (92 runs sampled)
```

### Master:

```
eval identifier x 870,112,252 ops/sec ±0.51% (94 runs sampled)
native identifier x 867,967,077 ops/sec ±0.76% (92 runs sampled)
eval complex x 7,587,671 ops/sec ±1.51% (88 runs sampled)
native complex x 867,284,566 ops/sec ±0.42% (93 runs sampled)
```

File: src/lib/parser.ts [hunk 1]
```diff
@@ -108,6 +108,8 @@ export class Parser<N extends Expression> {
         method.value,
         (right as Invoke).arguments as any
       );
+    } else if (right.type === 'Literal' && (right as Literal).value === null) {
```
Comment (justinfagnani) [inline src/lib/parser.ts:111]: I don't think it's possible to enter this case. The right-hand side of a `.` operator should always be an ID or Invoke. The test cases you have don't look like they enter here, they just have IDs of `nullable` and `nulled`.

File: src/test/parser_test.ts [hunk 2]
```diff
@@ -134,6 +135,12 @@ suite('Parser', function () {
     );
   });
 
+  test('should return null for a null property of the model', function () {
+    const astFact = new EvalAstFactory();
+    assert.equal(parser!.parse('data.nullable', astFact)?.evaluate({ data: null }), null);
```
Comment (justinfagnani) [inline src/test/parser_test.ts:140]: This test should be in eval_test.ts, and use the `expectEval` helper there.

**Review by justinfagnani — CHANGES_REQUESTED** [review]

File: src/test/parser_test.ts (hunk 2 above)
Comment (bennypowers) [reply src/test/parser_test.ts]: moved over and refactored, thanks

File: src/lib/parser.ts (hunk 1 above)
Comment (bennypowers) [reply src/lib/parser.ts]: confirmed; removed this case.

**Review by justinfagnani — APPROVED** [review]
Thanks!
